### ISSUE TITLE
Documentation: James Russell and Margaret Bradley

### ISSUE THREAD

**Issue by BradKML** [alfonsosemeraro/pyplutchik#2]
There are alternative mood models that can be considered a sub-mapping of Plutchik

James Russell's Circumplex model
- https://doi.org/10.3390/electronics8020164
- https://doi.org/10.1037/a0023980
- https://doi.org/10.1007/s12144-014-9219-4
- https://doi.org/10.15388/20-INFOR419

Margaret Bradley "Boomerang Model" with Appetitive and Defensive Directions
- https://psycnet.apa.org/buy/2001-10055-007
- https://doi.org/10.1007/978-3-319-28099-8_42-1
- http://doi.org/10.1145/2858036.2858205
- http://doi.org/10.1037/1528-3542.1.3.276
-  http://doi.org/10.3758/BRM.41.1.184

**Comment by alfonsosemeraro** [comment]
Hi!

Thanks for your suggestion. We will give it a look, and maybe update pyplutchik accordingly in a future version.
