### ISSUE TITLE
Corpus For Reference

### ISSUE THREAD

**Issue by BrandonKMLee** [alfonsosemeraro/pyplutchik#3]
- English
	- https://github.com/cjhutto/vaderSentiment
	- https://github.com/aesuli/SentiWordNet
	- https://github.com/nik0spapp/usent
	- https://github.com/bohana/sentlex
	- https://github.com/metalcorebear/NRCLex
	- https://github.com/zengyan-97/Sentiment-Lexicon
	- https://github.com/opener-project/VU-sentiment-lexicon
- Multi-lingual https://github.com/JULIELab/MEmoLon
- Foreign:
	- Persian: https://github.com/mhbashari/NRC-Persian-Lexicon
	- Arabic: https://github.com/motazsaad/emotion-lexicon
	- Greek: https://github.com/MKLab-ITI/greek-sentiment-lexicon
	- Chinese: https://github.com/fannix/Chinese-Sentiment-Lexicon
	- Indonesian: https://github.com/fajri91/InSet
	- Sinhala: https://github.com/binodmx/helasentilex
	- Urdu: https://github.com/awaisathar/urdu-sentiment-lexicon

**Comment by BrandonKMLee** [comment]
Thank you for using NRCLex in https://github.com/alfonsosemeraro/emolib

**Comment by alfonsosemeraro** [comment]
Thank you for all the references!
