### ISSUE TITLE
[error] TypeError: Axes.annotate() missing 1 required positional argument: 'text'

### ISSUE THREAD

**Issue by resaition** [alfonsosemeraro/pyplutchik#5]
Hi, 
I am new to this library and just tried the first example. I met this error.

**Comment by resaition** [comment]
Hi Alfonso,
Thanks for your effort and amazing job. I will try to use the code first and please let me know if you have done the pypi.

Sai

**Comment by resaition** [comment]
Hi Alfonso,
I have downloaded the code and tried to use it. This time the code works fine and no errors occur however I didn't see any results come out. Any suggestions? Thank you.

Sai

**Comment by alfonsosemeraro** [comment]
Hi Sai,

perhaps you're using it in the terminal? I can confirm that it's producing an output plot in IDEs and in Jupyter Notebooks/Lab.
You can explicitly import matplotlib and call the show function to display it (or the savefig function to save it):

`# all pyplutchik code

import matplotlib.pyplot as plt
plt.show();
`

This shouldn't be required in any IDE or notebook... what tool do you use for coding?

Alfonso

**Comment by resaition** [comment]
Hi Alfonso,
Thanks for your quick reply. The code works perfectly in Jupyter notebook. Thanks a lot!
