### ISSUE TITLE
TypeError: annotate() missing 1 required positional argument: 'text'

### ISSUE THREAD

**Issue by David75-cpu** [alfonsosemeraro/pyplutchik#6]
Hi,
I have tried new code, but still doesnt work. I have copied the updated code, anythin else I should do?

**Comment by alfonsosemeraro** [comment]
Hi David, just updated. Try now, please. 

If it doesn't work, would you report what error it returns to you?

Alfonso

**Comment by David75-cpu** [comment]
Hey, I think it works now, I tried it in carnets ios app, I just copied the whole code and that emotions values and just got first graph, Im gona try it now with other values you recommend in documentation and report back. Thank you.
