### ISSUE TITLE
ModuleNotFoundError: No module named 'pyplutchik'

### ISSUE THREAD

**Issue by gskarp** [alfonsosemeraro/pyplutchik#9]
Hello,
I have installed the library and just attempt to run the code included here without modifications.
I get the following error code:
`ModuleNotFoundError: No module named 'pyplutchik'
`
Any suggestions?

**Comment by alfonsosemeraro** [comment]
Hi gskarp, sorry for the late reply. Did you solve the problem?
Could you report here what did you attempt?

**Comment by gskarp** [comment]
Hi alfonso! Thanks for the reply. 
I forgot to use the env at the first time. When I used it, it worked fine.
I will use it in my research.

**Comment by alfonsosemeraro** [comment]
Thank you Yannis!
I'm glad to hear the package is useful for your research.
I am currently working on https://github.com/alfonsosemeraro/emolib, which
allows for *extraction* of statistically meaningful emotions scores, and
their visualization, and syntactic/semantic associations between words. All
together, these new features give you the possibility to focus on one
concept and investigate the semantic/emotional neighborhood of concepts
related to it.
The new library works but it's not 100% complete, and most of the
documentation is missing or out of date, but in the next few days I should
finalize it and release it asap.
Let me know if you have any questions!

Alfonso

**Comment by gskarp** [comment]
I plan to give it a try. Would it be possible to use private versions of NRC? Greek is not a good as its English lexicon, and I use to apply content specific lexicon to NRC

**Comment by alfonsosemeraro** [comment]
Yes, it is possible.

Default baseline for Greek is a translation of English NRC. However, one
may replace the *emotion_lexicon* and the *baseline* with custom lexicons.
I plan to write a function to handle this smoothly, while as of now it must
be done by hand.

Last: we are not experts of Greek and other languages, we just use
dictionaries. We plan to encourage native-speaker researchers to submit a
better version of the lexicon in their own language, to be included as
default in the library.

Alfonso

**Comment by gskarp** [comment]
I volunteer for Greek!
